import { Run } from "@/lib/types";

export const initialRuns: Run[] = [
  {
    id: "run_1",
    strategy: "atlas_momentum.py",
    datasetVersion: "Акции США v13",
    period: "2018-01-01 -> 2024-12-31",
    timeframe: "1D",
    params: {
      fees: "0.8 bps",
      slippage: "0.5 bps",
      execution: "VWAP",
      riskPerTrade: "0.5%",
      maxExposure: "25%",
      symbols: ["SPY", "QQQ", "IWM", "EFA", "EEM"],
      timeframe: "1D",
      period: "2018-01-01 -> 2024-12-31",
    },
    metrics: {
      pnl: 18.4,
      sharpe: 1.62,
      maxDrawdown: -9.7,
      trades: 842,
      winrate: 54.2,
      avgTrade: 0.12,
      feesImpact: -1.8,
    },
    diagnostics: {
      diagnosticsStatus: "mixed",
      diagnosticsSummary: "Strategy result is profitable but mixed because gains are uneven across stability segments.",
      risk: {
        totalPnl: 1840,
        totalReturnPct: 18.4,
        maxDrawdown: 970,
        maxDrawdownPct: 9.7,
        drawdownStart: "2022-03-14T00:00:00Z",
        drawdownEnd: "2022-06-16T00:00:00Z",
        recoveryBars: 42,
      },
      trades: {
        tradeCount: 842,
        winningTrades: 456,
        losingTrades: 386,
        winRate: 54.2,
        profitFactor: 1.34,
        averageWin: 18.4,
        averageLoss: -14.1,
        bestTrade: 104.2,
        worstTrade: -76.5,
        longestWinStreak: 8,
        longestLossStreak: 5,
        averageTradePnl: 2.18,
        medianTradePnl: 1.4,
      },
      stability: {
        status: "mixed",
        segments: [
          { segmentIndex: 1, from: "2018-01-01", to: "2019-09-30", pnl: 510, tradeCount: 211, maxDrawdown: 180, status: "strong" },
          { segmentIndex: 2, from: "2019-10-01", to: "2021-06-30", pnl: 640, tradeCount: 207, maxDrawdown: 220, status: "strong" },
          { segmentIndex: 3, from: "2021-07-01", to: "2023-03-31", pnl: -120, tradeCount: 214, maxDrawdown: 420, status: "weak" },
          { segmentIndex: 4, from: "2023-04-01", to: "2024-12-31", pnl: 810, tradeCount: 210, maxDrawdown: 260, status: "strong" },
        ],
      },
      warnings: [
        {
          code: "UNSTABLE_SEGMENTS",
          severity: "medium",
          message: "Stability segments are mixed or weak.",
        },
      ],
    },
    status: "done",
    artifacts: [
      { id: "log_1", label: "Лог выполнения", type: "log", size: "2.4 MB" },
      { id: "rep_1", label: "Отчет запуска", type: "report", size: "1.1 MB" },
      { id: "exp_1", label: "Пакет экспорта", type: "export", size: "4.8 MB" },
    ],
    createdAt: "2025-01-17 18:42",
    commit: "a7c9e2d",
    config: `fees: 0.8\nslippage: 0.5\nexecution: vwap\nrisk:\n  per_trade: 0.5%\n  max_exposure: 25%\n`,
    tags: ["baseline"],
    diff: { code: true, data: false, config: true },
  },
  {
    id: "run_2",
    strategy: "atlas_momentum.py",
    datasetVersion: "Акции США v12",
    period: "2016-01-01 -> 2023-12-31",
    timeframe: "1D",
    params: {
      fees: "0.8 bps",
      slippage: "0.6 bps",
      execution: "VWAP",
      riskPerTrade: "0.5%",
      maxExposure: "20%",
      symbols: ["SPY", "QQQ", "IWM", "EFA", "EEM"],
      timeframe: "1D",
      period: "2016-01-01 -> 2023-12-31",
    },
    metrics: {
      pnl: 15.1,
      sharpe: 1.41,
      maxDrawdown: -11.4,
      trades: 801,
      winrate: 52.9,
      avgTrade: 0.1,
      feesImpact: -2.1,
    },
    status: "done",
    artifacts: [
      { id: "log_2", label: "Лог выполнения", type: "log", size: "1.9 MB" },
      { id: "rep_2", label: "Отчет запуска", type: "report", size: "1.0 MB" },
    ],
    createdAt: "2025-01-17 16:03",
    commit: "a1c4f0b",
    config: `fees: 0.8\nslippage: 0.6\nexecution: vwap\nrisk:\n  per_trade: 0.5%\n  max_exposure: 20%\n`,
    tags: ["candidate"],
    diff: { code: false, data: true, config: true },
  },
  {
    id: "run_3",
    strategy: "atlas_momentum.py",
    datasetVersion: "Акции США v13",
    period: "2018-01-01 -> 2024-12-31",
    timeframe: "1D",
    params: {
      fees: "0.8 bps",
      slippage: "0.4 bps",
      execution: "TWAP",
      riskPerTrade: "0.6%",
      maxExposure: "25%",
      symbols: ["SPY", "QQQ", "IWM", "EFA", "EEM"],
      timeframe: "1D",
      period: "2018-01-01 -> 2024-12-31",
    },
    metrics: {
      pnl: 19.7,
      sharpe: 1.72,
      maxDrawdown: -9.2,
      trades: 864,
      winrate: 55.6,
      avgTrade: 0.13,
      feesImpact: -1.6,
    },
    status: "running",
    artifacts: [
      { id: "log_3", label: "Лог выполнения", type: "log", size: "1.2 MB" },
    ],
    createdAt: "2025-01-17 19:10",
    commit: "b2d8c5a",
    config: `fees: 0.8\nslippage: 0.4\nexecution: twap\nrisk:\n  per_trade: 0.6%\n  max_exposure: 25%\n`,
    tags: ["prod-like"],
    diff: { code: true, data: false, config: false },
  },
  {
    id: "run_4",
    strategy: "orbit_reversion.py",
    datasetVersion: "ETF внутри дня v21",
    period: "2022-01-01 -> 2024-12-31",
    timeframe: "15m",
    params: {
      fees: "1.2 bps",
      slippage: "0.9 bps",
      execution: "Market",
      riskPerTrade: "0.3%",
      maxExposure: "15%",
      symbols: ["SPY", "QQQ", "TLT", "GLD"],
      timeframe: "15m",
      period: "2022-01-01 -> 2024-12-31",
    },
    metrics: {
      pnl: 9.3,
      sharpe: 0.98,
      maxDrawdown: -12.6,
      trades: 1940,
      winrate: 49.1,
      avgTrade: 0.05,
      feesImpact: -3.4,
    },
    status: "queued",
    artifacts: [],
    createdAt: "2025-01-17 11:12",
    commit: "7c21ab9",
    config: `fees: 1.2\nslippage: 0.9\nexecution: market\nrisk:\n  per_trade: 0.3%\n  max_exposure: 15%\n`,
    tags: ["candidate"],
    diff: { code: true, data: true, config: false },
  },
  {
    id: "run_5",
    strategy: "ridge_carry.py",
    datasetVersion: "FX дневной v09",
    period: "2015-01-01 -> 2024-12-31",
    timeframe: "1D",
    params: {
      fees: "0.4 bps",
      slippage: "0.3 bps",
      execution: "VWAP",
      riskPerTrade: "0.4%",
      maxExposure: "30%",
      symbols: ["EURUSD", "USDJPY", "GBPUSD", "AUDUSD"],
      timeframe: "1D",
      period: "2015-01-01 -> 2024-12-31",
    },
    metrics: {
      pnl: 21.6,
      sharpe: 1.88,
      maxDrawdown: -7.8,
      trades: 620,
      winrate: 58.3,
      avgTrade: 0.16,
      feesImpact: -1.1,
    },
    status: "done",
    artifacts: [
      { id: "log_5", label: "Лог выполнения", type: "log", size: "1.3 MB" },
      { id: "rep_5", label: "Отчет запуска", type: "report", size: "900 KB" },
    ],
    createdAt: "2025-01-16 09:05",
    commit: "0fa71d2",
    config: `fees: 0.4\nslippage: 0.3\nexecution: vwap\nrisk:\n  per_trade: 0.4%\n  max_exposure: 30%\n`,
    tags: ["baseline", "prod-like"],
    diff: { code: false, data: false, config: false },
  },
  {
    id: "run_6",
    strategy: "ridge_carry.py",
    datasetVersion: "FX дневной v08",
    period: "2012-01-01 -> 2023-12-31",
    timeframe: "1D",
    params: {
      fees: "0.4 bps",
      slippage: "0.4 bps",
      execution: "VWAP",
      riskPerTrade: "0.4%",
      maxExposure: "28%",
      symbols: ["EURUSD", "USDJPY", "GBPUSD", "AUDUSD"],
      timeframe: "1D",
      period: "2012-01-01 -> 2023-12-31",
    },
    metrics: {
      pnl: 17.2,
      sharpe: 1.51,
      maxDrawdown: -10.9,
      trades: 588,
      winrate: 55.2,
      avgTrade: 0.11,
      feesImpact: -1.3,
    },
    status: "failed",
    artifacts: [
      { id: "log_6", label: "Лог выполнения", type: "log", size: "600 KB" },
    ],
    createdAt: "2025-01-16 08:12",
    commit: "0fa71d2",
    config: `fees: 0.4\nslippage: 0.4\nexecution: vwap\nrisk:\n  per_trade: 0.4%\n  max_exposure: 28%\n`,
    tags: ["candidate"],
    diff: { code: false, data: true, config: false },
  },
];
